FROM anaconda

MAINTAINER Ethan Wang <wange011@gatech.edu>

RUN apk update &&/
    apk add git nvidia-cuda tensorflow

RUN git clone https://github.com/louisabraham/python3-midi &&/
    python setup.py install    
